spring.application.name=HotelSystem

hotel.rooms.standard=5
hotel.rooms.deluxe=3
hotel.rooms.suite=2

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hoteldb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hotel}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hotel123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.sql-migration-separator=_
spring.flyway.locations=classpath:db/migration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5

springdoc.swagger-ui.path=/api/v1/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.path=/api/v1/openapi
springdoc.swagger-ui.operationsSorter=alpha

application.jwt.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.jwt.tokenExpiration=8640000
